### ISSUE TITLE
无

### ISSUE THREAD

**Issue by km1994** [jackaduma/awesome_LLMs_interview_notes#6]
无

**Comment by km1994** [comment]
若想做 LLMs 面经，麻烦自己收集问题，然后做回答，而不是盗人成果！！！

**Comment by jackaduma** [comment]
好的 老板。
从你的 github上 引用的， 没想到您那边 有公众号。
稍微 删除

**Comment by jackaduma** [comment]
> 若想做 LLMs 面经，麻烦自己收集问题，然后做回答，而不是盗人成果！！！

好的 老板。
从你的 github上 引用的， 没想到您那边 有公众号。
稍微 删除

**Comment by jackaduma** [comment]
> 若想做 LLMs 面经，麻烦自己收集问题，然后做回答，而不是盗人成果！！！

好的 老板。
从你的 github上 引用的， 并且也在开头 就表明了问题来自于您的github，标明了链接。
您的答案 收费。 我只是想基于问题 做个 免费的 问题线索提示。
您觉得有问题， 我可以删除。

**Comment by jackaduma** [comment]
好的 老板。
首先 本仓库是从您的 github上 引用的， 并且也在开头 就表明了问题来自于您的github，标明了链接。并不涉及 “公众号”。
其次，您的答案 是收费的。 本人只是想基于问题 为大家感兴趣又没什么钱的 做个 免费的 问题线索提示。

您觉得有问题， 我可以进行整改。

**Comment by jackaduma** [comment]
好的 老板。
首先 本仓库是从您的 github上 引用的， 并且也**在开头 就表明了问题来自于您的github，标明了链接**。并不涉及 “公众号”。
其次，您的答案 是收费的。 本人只是想基于问题，为家做个“免费的”问题的线索和提示。**并无任何盈利目的**。

您觉得有问题， 本人可以进行整改。
此致

**Comment by liguodongiot** [comment]
@jackaduma  大概是影响到他赚钱了吧，之前还有人给我反馈我公众号/知乎的很多文章，被他整理到知识星球靠信息差赚钱。也没有经过我的同意，是不是也算侵权。

![image](https://github.com/jackaduma/awesome_LLMs_interview_notes/assets/13220186/b0eaa767-0124-4e73-92aa-44f1423a93fb)

**Comment by Everfighting** [comment]
这个答主都是在各种渠道引流，然后打算赚钱。问题是题目也都是很通用的问题，怎么别人整理答案也碍到他了。真的是吃相太难看。支持楼主做好这个git，超越原来的哪个引流号！

**Comment by sherlock1987** [comment]
进星球了，看见问题确实是有过详细的整理，但是回答的质量不高，需要我二次整理。

**Comment by wufeim** [comment]
哪里来的侵不侵权，他那些题目难道是自己拍脑子想的？面试遇到了就是他自己的题了，网上看到汇总一下就是他自己的成果了呗。
